# @package _group_
common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  fp16_no_flatten_grads: true
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  no_epoch_checkpoints: true
  save_interval_updates: 50000
  keep_interval_updates: 1

distributed_training:
  distributed_world_size: 16
  ddp_backend: legacy_ddp

task:
  _name: masked_lm
  data: /fsx-wav2vec/abaevski/data/nlp/bookwiki_aml-full-mmap2-bin
  sample_break_mode: none
  tokens_per_sample: 512
  include_target_tokens: true
  random_token_prob: 0
  leave_unmasked_prob: 0
  mask_prob: 0.08
  mask_multiple_length: 1

criterion: model

dataset:
  batch_size: 16
  ignore_unused_valid_subsets: true
  skip_invalid_size_inputs_valid_test: true

optimizer:
  _name: composite
  groups:
    encoder:
      lr_float: 3e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-06
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 4000
    decoder:
      lr_float: 3e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-06
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 4000

lr_scheduler: pass_through

optimization:
  clip_norm: 1
  lr: [0.0003]
  max_update: 400000
  update_freq: [1]

model:
  _name: data2vec_text
  head_layers: 2
  average_top_k_layers: 10
  layer_norm_target_layer: true
  instance_norm_target_layer: false
  batch_norm_target_layer: false
  instance_norm_targets: false
  layer_norm_targets: false
  loss_scale: 1
  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 30000
  loss_beta: 4
  ema_transformer_layers_only: true
  
  transformer:
    dropout: 0.1
    attention_dropout: 0.1
    layernorm_embedding: true
    activation_fn: gelu
    no_scale_embedding: true
    max_source_positions: 512
    encoder:
      embed_dim: 768
      ffn_embed_dim: 3072
      layers: 12
      attention_heads: 12
      normalize_before: false
      learned_pos: true
      layerdrop: 0

  mae_style: true
  mae_decoder_dim: 768
  mae_decoder_layers: 1
  mae_encoder_decoder_attn: true
  mae_no_self_attn: true
  remask: true
  require_same_masks: true
  mae_conv_decoder_layers: 3
  mae_conv_decoder_groups: 4
  mae_conv_decoder_kernel: 5
  mae_conv_decoder_residual: False
  mae_decoder_dropout: 0.0
  use_alibi_encoder: False
  clone_batch: 1
