# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: mae_image_pretraining
  data: /datasets01/imagenet_full_size/061417/
  rebuild_batches: true
  local_cache_path: /scratch/cache_abaevski/imagenet
  key: source

dataset:
  num_workers: 10
  batch_size: 32
  skip_invalid_size_inputs_valid_test: true
  required_batch_size_multiple: 1
  validate_interval_updates: 10000
  valid_subset: val

distributed_training:
  distributed_world_size: 8
  ddp_backend: c10d

criterion:
  _name: model

optimization:
  max_update: 100000
  lr: [ 0.001 ]
  debug_param_names: true
  clip_norm: 4

optimizer:
  _name: composite
  dynamic_groups: true
  groups:
    default:
      lr_float: 1e-3
      optimizer:
        _name: adam
        adam_betas: [0.9,0.95]
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 8000

lr_scheduler: pass_through

model:
  _name: data2vec_visualizer

  depth: 1
  num_heads: 8
  embed_dim: 512
  layer_norm_first: false
  normalize_pixels: false
  linear_blocks: false
  from_decoder: true

  model_path: /private/home/abaevski/models/data2vec2/imagenet/base_500k.pt
