# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  all_gather_list_size: 70000
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: /private/home/abaevski/fairseq-py/examples/data2vec

checkpoint:
  save_interval: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: mAP
  maximize_best_checkpoint_metric: true

task:
  _name: audio_classification
  data: ???
  normalize: true
  labels: lbl

dataset:
  num_workers: 6
  max_tokens: 2560000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: eval
  validate_interval: 5

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 8

criterion:
  _name: model
  can_sum: false
  log_keys:
    - _predictions
    - _targets

optimization:
  max_update: 13000
  lr: [0.00006] # scratch 53-5

optimizer:
  _name: composite
  groups:
    pretrained:
      lr_float: 0.00003
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-08
      lr_scheduler:
        _name: cosine
        warmup_updates: 8000
    projection:
      lr_float: 0.0002
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-08
      lr_scheduler:
        _name: cosine
        warmup_updates: 3000

lr_scheduler: pass_through

model:
  _name: audio_classification
  model_path: ???
  apply_mask: true
  mask_prob: 0.45
  mask_length: 4 # scratch 1
  mask_channel_prob: 0.1
  mask_channel_length: 64
  layerdrop: 0.15
  dropout: 0
  activation_dropout: 0.1
  attention_dropout: 0.2
  feature_grad_mult: 0 # scratch 1
  label_mixup: true
  source_mixup: 0.5
  mixup_prob: 0.7
  same_mixup: false
  gain_mode: none
  prediction_mode: lin_softmax # scratch average_sigmoid

  freeze_finetune_updates: 2000
  final_dropout: 0.2

