# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: /fsx-wav2vec/abaevski/data/librispeech
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 6
  max_tokens: 1000000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 8
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm
    - ema_global_scale
    - ema_avg_scale
    - ema_weight_decay
    - max_x
    - max_y
    - smooth_loss
    - smooth_loss2

optimization:
  max_update: 100000
  lr: [0.00075]
  debug_param_names: true

optimizer:
  _name: composite
  groups:
    encoder:
      lr_float: 7.5e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-06
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 8000
    decoder:
      lr_float: 7.5e-6
      optimizer:
        _name: adam
        adam_betas: [ 0.9,0.98 ]
        adam_eps: 1e-06
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 8000

lr_scheduler: pass_through

model:
  _name: data2vec_audio
  extractor_mode: layer_norm
  encoder_layerdrop: 0.05
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 1.0
  encoder_embed_dim: 768

  mask_prob: 0.7
    mask_length: 5
    mask_noise_std: 0.01

    loss_beta: 0
    loss_scale: null

    instance_norm_target_layer: true
    layer_norm_target_layer: false
    layer_norm_targets: false

    average_top_k_layers: 8

    pos_conv_depth: 5
    conv_pos: 95

    clone_batch: 8

    ema_decay: 0.999
    ema_end_decay: 0.99999
    ema_anneal_end_step: 75000
    ema_transformer_only: true
    ema_layers_only: false

    require_same_masks: true
    mask_dropout: 0

    use_alibi_encoder: true

    mae_style: true
    pos_emb_type: CONV
    mae_decoder_pos_type: CONV
    mae_zero_pos: true

    mae_decoder_dim: 384
    mae_decoder_dropout: 0.1
    mae_conv_decoder_groups: 16
    mae_conv_decoder_kernel: 7
    mae_conv_decoder_layers: 4
    mae_conv_decoder_residual: true
