# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: /data/home/abaevski/fairseq-py/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: /fsx-wav2vec/abaevski/data/librivox/no_silence
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 8
  max_tokens: 1000000
#  batch_size: 4
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 64
  ddp_backend: c10d

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var

optimization:
  max_update: 600000
  debug_param_names: false

optimizer:
  _name: composite
  groups:
    encoder:
      lr_float: 3e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        adam_eps: 1e-06
        weight_decay: 0.01
      _name: tri_stage
        phase_ratio: [ 0.02,0.7,0.28 ]
    decoder:
      lr_float: 3e-6
      optimizer:
        _name: adam
        adam_betas: [ 0.9,0.98 ]
        adam_eps: 1e-06
        weight_decay: 0.01
      _name: tri_stage
        phase_ratio: [ 0.02,0.7,0.28 ]

lr_scheduler: pass_through

model:
  _name: data2vec_audio
  extractor_mode: layer_norm

  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16

  dropout: 0.1
  attention_dropout: 0.1
  activation_dropout: 0

  encoder_layerdrop: 0
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 1.0

  mask_prob: 0.7
  mask_length: 1

  loss_beta: 0
  loss_scale: null

  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: true

  average_top_k_layers: 10

  pos_conv_depth: 5
  conv_pos: 95

  clone_batch: 8

  ema_decay: 0.999
  ema_end_decay: 1.0
  ema_anneal_end_step: 400000
  ema_transformer_only: true
  ema_layers_only: false

  require_same_masks: true
  mask_dropout: 0

  mae_style: true
  pos_emb_type: CONV
  mae_decoder_pos_type: CONV
  mae_zero_pos: true
  mae_decoder_heads: 8
  mae_decoder_layers: 1
  mae_encoder_decoder_attn: true
  mae_no_self_attn: true

  mae_decoder_dim: 1024

