# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  fp16_no_flatten_grads: true
  user_dir: ???

checkpoint:
  save_interval: 5
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: mae_image_pretraining
  data: /datasets01/imagenet_full_size/061417/
  rebuild_batches: true
  local_cache_path: /scratch/cache/d2v/imagenet

dataset:
  num_workers: 6
  batch_size: 8
  skip_invalid_size_inputs_valid_test: true
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 16
  ddp_backend: c10d

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm

optimization:
  max_update: 375300
  lr: [0.0004]
  clip_norm: 0

optimizer:
  _name: composite
  groups:
    encoder_with_decay:
      lr_float: 4e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.95]
        weight_decay: 0.05
      lr_scheduler:
        _name: cosine
        warmup_updates: 50040
    encoder_no_decay:
      lr_float: 4e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.95]
        weight_decay: 0
      lr_scheduler:
        _name: cosine
        warmup_updates: 50040
    decoder_with_decay:
      lr_float: 4e-4
      optimizer:
        _name: adam
        adam_betas: [ 0.9,0.95 ]
        weight_decay: 0.05
      lr_scheduler:
        _name: cosine
        warmup_updates: 50040
    decoder_no_decay:
      lr_float: 4e-4
      optimizer:
        _name: adam
        adam_betas: [ 0.9,0.95 ]
        weight_decay: 0
      lr_scheduler:
        _name: cosine
        warmup_updates: 50040

lr_scheduler: pass_through

model:
  _name: d2v_mae
  ema_decay: 0.9997
  ema_end_decay: 1
  ema_anneal_end_step: 100000
  layer_norm_target_layer: true
  layer_norm_targets: true
  end_of_block_targets: true

  w2v_block: false
  alt_block: true
  layer_norm_first: false

  mask_ratio: 0.8
  mask_noise_std: 0.01

  decoder_embed_dim: 512
  average_top_k_layers: 10
  decoder_type: conv2d
  mae_conv_decoder_layers: 6
  mae_conv_decoder_kernel: 3
  mae_conv_decoder_groups: 16
  mae_conv_decoder_no_ln: false
  mae_conv_decoder_residual: true
  no_decoder_embed: true
  no_decoder_pos_embed: true
  loss_scale: 0

  clone_batch: 16

  depth: 24
  num_heads: 16
  embed_dim: 1024