# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: multimodal_pretraining
  audio_ratio: 4
  image_ratio: 1
  audio:
    data: /private/home/abaevski/data/librispeech/full
    max_sample_size: 250000
    min_sample_size: 32000
    normalize: true
  image:
    data: /datasets01/imagenet_full_size/061417
    local_cache_path: /scratch/cache_abaevski/imagenet
    key: source

dataset:
  num_workers: 8
  batch_size: 6
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 32
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm
    - masked_pct

optimization:
  max_update: 200000
  lr: [0.0005]
  clip_norm: 1
  debug_param_names: true

optimizer:
  _name: composite
  dynamic_groups: true
  groups:
    default:
      lr_float: 5e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.95]
        weight_decay: 0.05
      lr_scheduler:
        _name: cosine
        warmup_updates: 24000

lr_scheduler: pass_through

model:
  _name: data2vec_multi

  depth: 8
  embed_dim: 768
  clone_batch: 8

  ema_decay: 0.9995
  ema_end_decay: 0.99999
  ema_anneal_end_step: 75000

  average_top_k_layers: 8
  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: false
  end_of_block_targets: false

  encoder_dropout: 0
  post_mlp_drop: 0
  attention_dropout: 0
  activation_dropout: 0

  ema_encoder_only: false

  modalities:
    audio:
      conv_pos_depth: 5
      conv_pos_width: 95
      conv_pos_groups: 16
      prenet_depth: 4
      mask_prob: 0.7
      mask_length: 5
      mask_noise_std: 0.01
      mask_dropout: 0
      add_masks: false
      ema_local_encoder: false
      use_alibi_encoder: true
      prenet_layerdrop: 0
      prenet_dropout: 0.1
      learned_alibi_scale: true
      learned_alibi_scale_per_head: true
      decoder:
        input_dropout: 0.1
        decoder_dim: 384
        decoder_groups: 16
        decoder_kernel: 7
        decoder_layers: 4
    image:
      mask_prob: 0.8
      mask_length: 1
      mask_noise_std: 0.01
      prenet_depth: 4
      ema_local_encoder: true
      num_extra_tokens: 1
      use_alibi_encoder: false
      decoder:
        decoder_dim: 512
        decoder_groups: 16
        decoder_kernel: 3
        decoder_layers: 6
        final_layer_norm: true
        input_dropout: 0
