# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: multimodal_pretraining
  audio_ratio: 20
  text_ratio: 1
  audio:
    data: /private/home/abaevski/data/librispeech/full
    max_sample_size: 250000
    min_sample_size: 32000
    normalize: true
    precompute_mask_config: {}
  text:
    data: /datasets01/bookwiki_CC-NEWS_openwebtext_stories-mmap2-bin/121219/bookwiki_CC-NEWS_openwebtext_stories-mmap2-bin
    sample_break_mode: none
    tokens_per_sample: 512
    include_target_tokens: true
    random_token_prob: 0
    leave_unmasked_prob: 0
    mask_prob: 0.24
    mask_multiple_length: 2
    include_index: True
    skip_masking: True
    d2v2_multi: True

dataset:
  num_workers: 8
  batch_size: 4
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 32
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var_TEXT
    - pred_var_TEXT
    - target_var_IMAGE
    - pred_var_IMAGE
    - target_var_AUDIO
    - pred_var_AUDIO
    - model_norm
    - ema_norm
    - masked_pct

optimization:
  max_update: 200000
  lr: [0.0003]
  clip_norm: 1
  debug_param_names: true

optimizer:
  _name: composite
  dynamic_groups: true
  groups:
    default:
      lr_float: 3e-4
      optimizer:
        _name: adam
        adam_betas: [0.9,0.98]
        weight_decay: 0.01
      lr_scheduler:
        _name: cosine
        warmup_updates: 12000

lr_scheduler: pass_through

model:
  _name: data2vec_multi

  depth: 10
  embed_dim: 768
  clone_batch: 8

  layer_norm_first: false

  ema_decay: 0.999
  ema_end_decay: 0.99999
  ema_anneal_end_step: 75000

  average_top_k_layers: 8
  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: false
  end_of_block_targets: false

  encoder_dropout: 0
  post_mlp_drop: 0
  attention_dropout: 0
  activation_dropout: 0

  ema_encoder_only: false

  modalities:
    audio:
      feature_encoder_spec: '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] + [(512,2,2)]'
      conv_pos_depth: 5
      conv_pos_width: 95
      conv_pos_groups: 16
      prenet_depth: 2
      mask_prob: 0.5
      mask_prob_adjust: 0.05
      inverse_mask: false
      mask_length: 5
      mask_noise_std: 0.01
      mask_dropout: 0
      add_masks: false
      ema_local_encoder: false
      use_alibi_encoder: true
      prenet_layerdrop: 0
      prenet_dropout: 0.1
      learned_alibi_scale: true
      learned_alibi_scale_per_head: true
      decoder:
        input_dropout: 0.1
        decoder_dim: 384
        decoder_groups: 16
        decoder_kernel: 7
        decoder_layers: 4
    text:
      mask_prob: 0.24
      mask_length: 2
      mask_noise_std: 0.01
      prenet_depth: 4
      decoder:
        input_dropout: 0.1
        decoder_dim: 768
        decoder_groups: 1
        decoder_kernel: 9
        decoder_layers: 5
        final_layer_norm: false
        decoder_residual: false
        projection_layers: 1
        projection_ratio: 2.0
